openapi: '3.0.0'
paths:
  /api/user/:
    get:
      tags:
        - User
      security:
        - bearerAuth: []
      responses:
        200:
          description: List of users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
components:
  schemas:
    User:
      type: object
      required:
        - _id
        - email
        - firstname
        - lastname
        - createdAt
        - updatedAt
      properties:
        _id:
          type: string
          format: uuid
        email:
          type: string
          format: email
          maxLength: 100
        firstname:
          type: string
          maxLength: 100
        lastname:
          type: string
          maxLength: 100
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
