openapi: '3.0.0'
paths:
  /api/blog:
    post:
      tags:
        - Blog
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  required: true
                  maxLength: 100
                description:
                  type: string
                  maxLength: 500
      responses:
        201:
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/Blog'
    get:
      tags:
        - Blog
      security:
        - bearerAuth: []
      responses:
        200:
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Blog'
  /api/blog/{id}:
    put:
      tags:
        - Blog
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  maxLength: 100
                description:
                  type: string
                  maxLength: 500
      responses:
        200:
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/Blog'
    get:
      tags:
        - Blog
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/Blog'
    delete:
      tags:
        - Blog
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            format: uuid
      responses:
        204:
components:
  schemas:
    Blog:
      type: object
      required:
        - _id
        - title
        - description
        - createdAt
        - updatedAt
        - create_by_name
        - updated_by_name
      properties:
        _id:
          type: string
          format: uuid
        title:
          type: string
          maxLength: 100
        description:
          type: string
          maxLength: 500
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        create_by_name:
          type: string
        updated_by_name:
          type: string
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
